package fr.atlasos.connect

import android.graphics.Color
import android.graphics.Typeface
import android.graphics.drawable.GradientDrawable
import android.os.Bundle
import android.text.InputType
import android.view.Gravity
import android.view.ViewGroup
import android.widget.*
import androidx.activity.ComponentActivity
import androidx.health.connect.client.HealthConnectClient
import androidx.health.connect.client.PermissionController
import androidx.health.connect.client.permission.HealthPermission
import androidx.health.connect.client.records.*
import androidx.lifecycle.lifecycleScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

class MainActivity : ComponentActivity() {
    private val navy=Color.rgb(2,13,24);private val card=Color.rgb(7,29,45);private val cyan=Color.rgb(49,214,255);private val atlasTextColor=Color.rgb(235,246,255);private val muted=Color.rgb(143,168,187);private var autoSyncStarted=false
    private val permissionLabels by lazy { linkedMapOf(HealthPermission.getReadPermission(ExerciseSessionRecord::class) to "Exercice",HealthPermission.getReadPermission(SleepSessionRecord::class) to "Sommeil",HealthPermission.getReadPermission(HeartRateRecord::class) to "Fréquence cardiaque",HealthPermission.getReadPermission(RestingHeartRateRecord::class) to "FC au repos",HealthPermission.getReadPermission(DistanceRecord::class) to "Distance",HealthPermission.getReadPermission(SpeedRecord::class) to "Vitesse",HealthPermission.getReadPermission(ElevationGainedRecord::class) to "Dénivelé",HealthPermission.getReadPermission(TotalCaloriesBurnedRecord::class) to "Calories totales",HealthPermission.getReadPermission(ActiveCaloriesBurnedRecord::class) to "Calories actives",HealthPermission.getReadPermission(BasalMetabolicRateRecord::class) to "Métabolisme basal",HealthPermission.getReadPermission(StepsRecord::class) to "Pas",HealthPermission.getReadPermission(FloorsClimbedRecord::class) to "Étages",HealthPermission.getReadPermission(StepsCadenceRecord::class) to "Cadence",HealthPermission.getReadPermission(PowerRecord::class) to "Puissance",HealthPermission.getReadPermission(WeightRecord::class) to "Poids",HealthPermission.getReadPermission(BodyFatRecord::class) to "Masse grasse",HealthPermission.getReadPermission(HeightRecord::class) to "Taille",HealthPermission.getReadPermission(LeanBodyMassRecord::class) to "Masse maigre",HealthPermission.getReadPermission(BodyWaterMassRecord::class) to "Eau corporelle",HealthPermission.getReadPermission(BoneMassRecord::class) to "Masse osseuse",HealthPermission.getReadPermission(Vo2MaxRecord::class) to "VO2max",HealthPermission.getReadPermission(HeartRateVariabilityRmssdRecord::class) to "VFC",HealthPermission.getReadPermission(OxygenSaturationRecord::class) to "SpO2",HealthPermission.getReadPermission(RespiratoryRateRecord::class) to "Fréquence respiratoire",HealthPermission.getReadPermission(BodyTemperatureRecord::class) to "Température",HealthPermission.getReadPermission(BloodPressureRecord::class) to "Pression artérielle",HealthPermission.getReadPermission(HydrationRecord::class) to "Hydratation",HealthPermission.getReadPermission(NutritionRecord::class) to "Nutrition") }
    private val cyclingCadencePermission get()=HealthPermission.getReadPermission(CyclingPedalingCadenceRecord::class)
    private val dataPermissions get()=permissionLabels.keys.toSet()+cyclingCadencePermission;private val permissions get()=dataPermissions+HealthPermission.PERMISSION_READ_HEALTH_DATA_HISTORY
    private lateinit var server:EditText;private lateinit var code:EditText;private lateinit var status:TextView;private lateinit var syncButton:Button
    private val requestPermissions=registerForActivityResult(PermissionController.createRequestPermissionResultContract()){lifecycleScope.launch{val granted=HealthConnectClient.getOrCreate(this@MainActivity).permissionController.getGrantedPermissions();showStatus(permissionStatus(dataPermissions-granted,granted),(dataPermissions-granted).isEmpty());autoSyncStarted=false;autoSyncOnOpen()}}
    override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);window.statusBarColor=navy;window.navigationBarColor=navy;val page=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;gravity=Gravity.CENTER_HORIZONTAL;setPadding(dp(24),dp(30),dp(24),dp(32));setBackgroundColor(navy)};page.addView(ImageView(this).apply{setImageResource(R.drawable.atlas_logo);scaleType=ImageView.ScaleType.CENTER_CROP},LinearLayout.LayoutParams(dp(82),dp(82)).apply{bottomMargin=dp(16)});page.addView(TextView(this).apply{text="ATLAS CONNECT";textSize=26f;setTextColor(atlasTextColor);gravity=Gravity.CENTER;setTypeface(typeface,Typeface.BOLD);letterSpacing=.08f});page.addView(TextView(this).apply{text="Votre passerelle personnelle vers Atlas OS";textSize=14f;setTextColor(muted);gravity=Gravity.CENTER},match().apply{topMargin=dp(5);bottomMargin=dp(24)});val cc=verticalCard();cc.addView(sectionTitle("CONNEXION ATLAS"));server=field("Adresse du serveur Atlas");code=field("Code d’association à 6 chiffres").apply{inputType=InputType.TYPE_CLASS_NUMBER};cc.addView(server,match().apply{topMargin=dp(12)});cc.addView(code,match().apply{topMargin=dp(10)});cc.addView(actionButton("Associer ce téléphone",false){pair()},match(dp(48)).apply{topMargin=dp(12)});page.addView(cc,match());val sc=verticalCard();sc.addView(sectionTitle("SANTÉ ET ACTIVITÉS"));sc.addView(TextView(this).apply{text="À l’ouverture, Atlas vérifie automatiquement Santé Connect. Le bouton Synchroniser utilise la même synchronisation différentielle.";textSize=14f;setTextColor(muted);setLineSpacing(0f,1.15f)},match().apply{topMargin=dp(8)});sc.addView(actionButton("Demander les autorisations manquantes",false){requestPermissions.launch(permissions)},match(dp(48)).apply{topMargin=dp(16)});syncButton=actionButton("Synchroniser Atlas",true){sync()};sc.addView(syncButton,match(dp(56)).apply{topMargin=dp(10)});page.addView(sc,match().apply{topMargin=dp(16)});status=TextView(this).apply{text="Non associé";textSize=14f;setTextColor(muted);gravity=Gravity.CENTER;setPadding(dp(12),dp(15),dp(12),dp(15));background=rounded(Color.rgb(5,24,38),Color.rgb(17,61,84),14f)};page.addView(status,match().apply{topMargin=dp(16)});setContentView(ScrollView(this).apply{isFillViewport=true;setBackgroundColor(navy);addView(page)});val prefs=getSharedPreferences("atlas",MODE_PRIVATE);server.setText(prefs.getString("server",""));if(prefs.contains("token")){AtlasAutoSync.schedule(this);autoSyncOnOpen()}}
    private fun permissionStatus(m:Set<String>,g:Set<String>):String{val n=m.map{permissionLabels[it]?:if(it==cyclingCadencePermission)"Cadence vélo" else it};val h=HealthPermission.PERMISSION_READ_HEALTH_DATA_HISTORY !in g;return when{n.isEmpty()&&!h->"Toutes les autorisations Santé Connect sont accordées";n.isEmpty()->"Historique Santé Connect non autorisé";else->"Non autorisé : ${n.joinToString(", ")}${if(h) " · Historique" else ""}"}}
    private suspend fun currentPermissionStatus():Pair<Set<String>,String>{val g=HealthConnectClient.getOrCreate(this).permissionController.getGrantedPermissions();val m=dataPermissions-g;return m to permissionStatus(m,g)}
    private fun autoSyncOnOpen(){if(autoSyncStarted)return;val p=getSharedPreferences("atlas",MODE_PRIVATE);if(!p.contains("token")||p.getString("server","").isNullOrBlank())return;autoSyncStarted=true;lifecycleScope.launch{runDifferentialSync("Vérification Santé Connect…")}}
    private suspend fun runDifferentialSync(start:String){try{val(missing,missingText)=currentPermissionStatus();if(missing.size==dataPermissions.size){showStatus("Aucune donnée Santé Connect autorisée");return};showStatus(start);val count=withContext(Dispatchers.Default){HealthChangeSync(this@MainActivity).run{p,m->if(p<95)runOnUiThread{showStatus("$m · $p %")}}};val suffix=if(missing.isEmpty())"" else "\n$missingText";showStatus((if(count==0)"Atlas à jour · aucune nouvelle donnée" else "Atlas à jour · $count élément(s) transmis")+suffix,true)}catch(e:Exception){showStatus("Synchronisation : ${e.message?:"échec"}")}}
    private fun pair()=lifecycleScope.launch{showStatus("Association en cours…");try{val token=AtlasTransport.pair(server.text.toString(),code.text.toString());getSharedPreferences("atlas",MODE_PRIVATE).edit().putString("server",server.text.toString().trimEnd('/')).putString("token",token).apply();AtlasAutoSync.schedule(this@MainActivity);showStatus("Association réussie",true);autoSyncStarted=false;autoSyncOnOpen()}catch(e:Exception){showStatus(e.message?:"Échec de l’association")}}
    private fun sync()=lifecycleScope.launch{syncButton.isEnabled=false;try{val s=server.text.toString().trim().trimEnd('/');require(s.isNotEmpty()){"Adresse du serveur Atlas manquante."};getSharedPreferences("atlas",MODE_PRIVATE).edit().putString("server",s).apply();runDifferentialSync("Vérification manuelle Santé Connect…")}finally{syncButton.isEnabled=true}}
    private fun showStatus(m:String,ok:Boolean=false){if(!::status.isInitialized)return;status.text=m;status.setTextColor(if(ok)Color.rgb(89,234,181)else muted)};private fun verticalCard()=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(18),dp(18),dp(18),dp(18));background=rounded(card,Color.rgb(16,65,88),20f)};private fun sectionTitle(v:String)=TextView(this).apply{text=v;textSize=12f;setTextColor(cyan);setTypeface(typeface,Typeface.BOLD);letterSpacing=.12f};private fun field(h:String)=EditText(this).apply{hint=h;setHintTextColor(Color.rgb(100,128,148));setTextColor(atlasTextColor);textSize=14f;setSingleLine(true);setPadding(dp(14),0,dp(14),0);background=rounded(Color.rgb(3,20,32),Color.rgb(20,75,100),12f)};private fun actionButton(l:String,p:Boolean,a:()->Unit)=Button(this).apply{text=l;textSize=if(p)16f else 14f;setTextColor(if(p)navy else atlasTextColor);setTypeface(typeface,Typeface.BOLD);isAllCaps=false;background=rounded(if(p)cyan else Color.rgb(10,42,61),if(p)cyan else Color.rgb(23,91,120),14f);setOnClickListener{a()}};private fun rounded(f:Int,s:Int,r:Float)=GradientDrawable().apply{shape=GradientDrawable.RECTANGLE;setColor(f);setStroke(dp(1),s);cornerRadius=dp(r.toInt()).toFloat()};private fun match(h:Int=ViewGroup.LayoutParams.WRAP_CONTENT)=LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,h);private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt()
}
